BookKeeper_app_root/BookKeeper_app/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

# Use include() to add URLS from the catalog application and authentication system
# Use static() to add url mapping to serve static files during development (only)




urlpatterns = [
    path("" , include("pages.urls")) ,
    path("admin/", admin.site.urls),
    path("booklist", include("my_library.urls")),
    path("currently_reading/", include("currently_reading.urls")),
    # path('next_in_line/', include('next_in_line.urls')),
    # path('loans/', include('loans.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BookKeeper_app_root/currently_reading/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('currently_reading/', views.Current, name='currently_reading'),
]

BookKeeper_app_root/loans/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('loans/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'loans/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]

BookKeeper_app_root/next_in_line/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('next_in_line/', views.Next_in_line, name='next_in_line'),
]

BookKeeper_app_root/currently_reading/models.py
from django.db import models

# Create your models here.
class Current(models.Model):
    
        def __str__(self):
            return self.book

BookKeeper_app_root/loans/models.py
from django.db import models
from django.contrib.auth.models import User
from my_library.models import Book, Status
from django.urls import reverse  # To generate URLS by reversing URL patterns
from datetime import date

# Create your models here.


        
class BookInstance(models.Model):
    booktitle = models.ForeignKey(Book, on_delete=models.CASCADE)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.ForeignKey(Status,on_delete=models.CASCADE)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '({0})'.format(self.booktitle)

BookKeeper_app_root/my_library/models.py
# Create your models here.
from django.db import models
from django.urls import reverse  # To generate URLS by reversing URL patterns
from django.contrib.auth.models import User  # Required to assign User as a borrower


STATUS_CHOICES = [
        ( 'On_loan' , 'On_loan'),
        ( 'Available', 'Available'),
        ( 'Reserved', 'Reserved'),
        ( 'Currently_reading', 'Currently_reading'),
        ( 'Next_in_line', 'Next_in_line'),
        ( 'Done_reading', 'Done_reading')
]

class Status(models.Model):
        status = models.CharField(max_length=20,
        choices= STATUS_CHOICES,
        help_text='Book availability')
        
        def __str__(self):
            return self.status 
        

LANGUAGE_CHOICES = [
        ('English','English'),
        ('Portuguese','Portuguese'),
        ('Spanish','Spanish'),
        ('Hebrew', 'Hebrew'),
        ('Italian','Italian'),
        ('French', 'French'),
    ]

class Language(models.Model):

    language = models.CharField(
    max_length=15,
    choices= LANGUAGE_CHOICES,
    help_text='Language')
            
    def __str__(self):
        return self.language        

class Book(models.Model):
    """Model representing a book."""
    book_cover = models.ImageField(upload_to= 'media/' , null=True)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50, default="Unkown")
    language = models.ForeignKey(Language, related_name='books',on_delete=models.CASCADE)
    summary = models.TextField(max_length=1000, help_text="Enter a brief summary of the book")
    pg_num = models.IntegerField()
    status = models.ForeignKey(Status, related_name='books',on_delete=models.CASCADE)
    
 

BookKeeper_app_root/next_in_line/models.py
from django.db import models

# Create your models here.
class Next(models.Model):
    
        def __str__(self):
            return self.book

BookKeeper_app_root/currently_reading/views.py
from django.shortcuts import render

# Create your views here.


def Current(request):
         return render(request, 'currently_reading.html')

BookKeeper_app_root/loans/views.py
from django.shortcuts import render, get_object_or_404
from .models import  Book, BookInstance
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from my_library.forms import CreateBookForm
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'loans.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='1').order_by('due_back')


# Added as part of challenge!

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all books on loan. Only visible to users with can_mark_returned permission."""
    model = BookInstance
    permission_required = 'booklist.can_mark_returned'
    template_name = 'loans.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='1').order_by('due_back')

    def renew_book_librarian(request, pk):
        """View function for renewing a specific BookInstance by librarian."""
        book_instance = get_object_or_404(BookInstance, pk=pk)

        # If this is a POST request then process the Form data
        if request.method == 'POST':

            # Create a form instance and populate it with data from the request (binding):
            form = CreateBookForm(request.POST)

            # Check if the form is valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
                book_instance.due_back = form.cleaned_data['renewal_date']
                book_instance.save()

                # redirect to a new URL:
                return HttpResponseRedirect(reverse('all-borrowed'))

        # If this is a GET (or any other method) create the default form
        else:
            proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=6)
            form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

        context = {
            'form': form,
            'book_instance': book_instance,
        }

        return render(request, 'loans.html', context)

BookKeeper_app_root/next_in_line/views.py
from django.shortcuts import render

# Create your views here.

def Next_in_line(request):
    return render(request, 'next_in_line.html')

BookKeeper_app_root/templates/404-Not-Found-Template.html
<!DOCTYPE html>
<html style="font-size: 16px;"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="404"><meta name="description" content="">
    <title></title>
    <link rel="stylesheet" href="/capp.nicepage.com/a21fecafd2132f518d14dad02d382c1b3e8867da/nicepage.css" media="screen" class="u-static-style"><link rel="stylesheet" href="nicepage.css" media="screen">
    <script class="u-script" type="text/javascript" src="//capp.nicepage.com/assets/jquery-1.9.1.min.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="//capp.nicepage.com/a21fecafd2132f518d14dad02d382c1b3e8867da/nicepage.js" defer=""></script>
<meta name="generator" content="Nicepage 5.2.4, nicepage.com"><link rel="stylesheet" data-font="Annie+Use+Your+Telescope:400" href="https://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope:400"></head>
<body class="u-body u-xl-mode" data-style="page-404-template-1" data-posts="" data-global-section-properties="{&quot;code&quot;:&quot;PAGE_404&quot;,&quot;colorings&quot;:{&quot;light&quot;:[&quot;clean&quot;,&quot;clean&quot;],&quot;colored&quot;:[&quot;clean&quot;,&quot;clean&quot;,&quot;clean&quot;],&quot;dark&quot;:[&quot;clean&quot;,&quot;clean&quot;,&quot;clean&quot;]},&quot;isPreset&quot;:true}" data-source="fix" data-lang="pt" data-page-sections-style="[{&quot;name&quot;:&quot;page-404-1&quot;,&quot;margin&quot;:&quot;both&quot;,&quot;repeat&quot;:false}]" data-page-coloring-types="{&quot;light&quot;:[&quot;clean&quot;,&quot;clean&quot;],&quot;colored&quot;:[&quot;clean&quot;,&quot;clean&quot;,&quot;clean&quot;],&quot;dark&quot;:[&quot;clean&quot;,&quot;clean&quot;,&quot;clean&quot;]}" data-page-category="404"><section class="u-align-center u-clearfix u-block-b79c-9" custom-posts-hash="T" data-section-properties="{&quot;margin&quot;:&quot;both&quot;,&quot;stretch&quot;:true}" data-id="b79c" data-style="page-404-1" id="sec-a993">
  <div class="u-clearfix u-sheet u-valign-middle u-block-b79c-2">
    <h1 class="u-text u-text-default u-text-palette-2-base u-block-b79c-11">404</h1>
    <p class="u-text u-text-default u-text-not-found-message u-block-b79c-10">sorry, pa​ge not found</p>
    <p class="u-text u-block-b79c-5">The page you are looking for was moved, removed, renamed or might never existed</p>
    <a href="" class="u-active-white u-border-2 u-border-active-black u-border-black u-border-hover-black u-btn u-button-style u-hover-white u-palette-2-light-2 u-text-active-black u-text-body-alt-color u-text-hover-black u-block-b79c-6">Go to homepage</a>
  </div>
  <style data-mode="XL">@media (min-width: 1200px) {
  .u-block-b79c-9 {
    background-image: none;
  }
  .u-block-b79c-2 {
    min-height: 100vh;
  }
  .u-block-b79c-11 {
    font-size: 12.5rem;
    font-weight: 700;
    margin-top: 60px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-10 {
    font-size: 1.875rem;
    font-weight: 700;
    line-height: 1;
    text-transform: uppercase;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-5 {
    background-image: none;
    font-size: 1.5rem;
    width: 525px;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-6 {
    border-style: solid;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 4px;
    background-image: none;
    align-self: center;
    margin-top: 30px;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: 60px;
    padding-top: 10px;
    padding-right: 54px;
    padding-bottom: 10px;
    padding-left: 52px;
  }
}</style>
  <style data-mode="LG">@media (max-width: 1199px) and (min-width: 992px) {
  .u-block-b79c-9 {
    background-image: none;
  }
  .u-block-b79c-2 {
    min-height: 100vh;
  }
  .u-block-b79c-11 {
    font-size: 12.5rem;
    font-weight: 700;
    margin-top: 60px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-10 {
    font-size: 1.875rem;
    font-weight: 700;
    line-height: 1;
    text-transform: uppercase;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-5 {
    background-image: none;
    font-size: 1.5rem;
    width: 525px;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-6 {
    background-image: none;
    border-style: solid;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 4px;
    align-self: center;
    margin-top: 30px;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: 60px;
    padding-top: 10px;
    padding-right: 54px;
    padding-bottom: 10px;
    padding-left: 52px;
  }
}</style>
  <style data-mode="MD">@media (max-width: 991px) and (min-width: 768px) {
  .u-block-b79c-9 {
    background-image: none;
  }
  .u-block-b79c-2 {
    min-height: 100vh;
  }
  .u-block-b79c-11 {
    font-size: 12.5rem;
    font-weight: 700;
    margin-top: 60px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-10 {
    font-size: 1.875rem;
    font-weight: 700;
    line-height: 1;
    text-transform: uppercase;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-5 {
    background-image: none;
    font-size: 1.5rem;
    width: 525px;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-6 {
    background-image: none;
    border-style: solid;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 4px;
    align-self: center;
    margin-top: 30px;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: 60px;
    padding-top: 10px;
    padding-right: 54px;
    padding-bottom: 10px;
    padding-left: 52px;
  }
}</style>
  <style data-mode="SM" data-visited="true">@media (max-width: 767px) and (min-width: 576px) {
  .u-block-b79c-9 {
    background-image: none;
  }
  .u-block-b79c-2 {
    min-height: 599px;
  }
  .u-block-b79c-11 {
    font-size: 12.5rem;
    font-weight: 700;
    margin-top: 60px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-10 {
    font-size: 1.875rem;
    font-weight: 700;
    line-height: 1;
    text-transform: uppercase;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-5 {
    background-image: none;
    font-size: 1.5rem;
    width: 525px;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-6 {
    background-image: none;
    border-style: solid;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 4px;
    align-self: center;
    margin-top: 30px;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: 60px;
    padding-top: 10px;
    padding-right: 54px;
    padding-bottom: 10px;
    padding-left: 52px;
  }
}</style>
  <style data-mode="XS" data-visited="true">@media (max-width: 575px) {
  .u-block-b79c-9 {
    background-image: none;
  }
  .u-block-b79c-2 {
    min-height: 525px;
  }
  .u-block-b79c-11 {
    font-size: 7.5rem;
    font-weight: 700;
    margin-top: 60px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-10 {
    font-size: 1.5rem;
    font-weight: 700;
    line-height: 1;
    text-transform: uppercase;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-5 {
    background-image: none;
    font-size: 1.25rem;
    width: 340px;
    margin-top: 20px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-b79c-6 {
    background-image: none;
    border-style: solid;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 4px;
    align-self: center;
    margin-top: 30px;
    margin-left: 0;
    margin-right: 0;
    margin-bottom: 60px;
    padding-top: 10px;
    padding-right: 54px;
    padding-bottom: 10px;
    padding-left: 52px;
  }
}</style>
</section>
</body></html>

BookKeeper_app_root/templates/book_add.html
{%load static%}
 

<!DOCTYPE html>
<html style="font-size: 16px;" lang="ena">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <title>Add Book</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css'%}" media="screen">
    <link rel="stylesheet" href="{% static 'css/bookadd.css'%}" media="screen">
    <meta name="generator" content="Nicepage 5.2.4, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i|Annie+Use+Your+Telescope:400">
    <meta name="generator" content="Nicepage 5.2.4, nicepage.com">
    <meta name="referrer" content="origin">
  </head>

  <body class="u-body" data-lang="ena">
  

  {% include "partials/_navbar.html" %}


<div class="formcss">
      <div>
        <h1>Add a new book</h1>
      </div>

          <img class="u-image u-image-contain" src="{% static 'images/girl-reading-book-3863818-3238408.png'%}"  alt="" data-image-width="639" data-image-height="450" style="
              height: 300px;
              width: 300px;
              margin-left: 40%;
              margin-right: 40%;
          ">


            <form method="post" enctype="multipart/form-data"
            style="
            padding-top: 50px;
            padding-right: 20%;
            padding-left: 20%;
            padding-bottom: 50px;
            width: 45%;">
            
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Submit">
            </form> 
</div>
 <!--Form--> 



{% comment %} <div class="container">
<section class="u-clearfix u-section-1" id="sec-fc0d">
  <div class="u-clearfix u-sheet u-sheet-1">
 <!--Image--> 
      <img class="u-image u-image-contain u-image-default u-image-1" src="(../static/images/girl-reading-book-3863818-3238408.png)" alt="" data-image-width="639" data-image-height="450">
<!--Bookcover-->     
    <div class="u-form-group u-form-message u-label-top">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
             <div class="u-form-group u-label-top u-form-group-1"> 
             <p>
            <label for="id_book_cover" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-1">Book cover</label>
            {% csrf_token %}
            <input type="file" name="upload" accept=".jpeg, .pdf, .png, .jpg, .svg" value="Submit"> 
            </p> 
         </div> 
 <!--Book title-->    
 <div class="u-form-group u-form-message u-label-top"> 
 <p> 
  <label for="id_title"class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-2">BOOK TITLE</label>
  {% csrf_token %}
  <input type="text" placeholder="ENTER THE BOOK TITLE" name="title" maxlength="50" required="" id="id_title" control-id="ControlID-2" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-2"> 
 </p> 
 </div> 

 <!--Author-->  
 <div class="u-form-group u-form-message u-label-top">  
  <p>
    <label for="id_author" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-3">AUTHOR</label>
    {% csrf_token %}
    <input type="text" placeholder="LAST NAME, NAME" name="author" value="Unkown" maxlength="50" required="" id="id_author" control-id="ControlID-3" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-3"> 
  </p>
</div>

 <!--Language-->   
<div class="u-form-group u-form-partition-factor-2 u-form-select u-label-top u-form-group-6">
  <p>
    <label for="id_language" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-6">Language:</label>
    {% csrf_token %}
      <div class="u-form-select-wrapper">
        <select name="language" required="" id="id_language" control-id="ControlID-4" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-6" required="required">
          <option value="" selected="">---------</option>
          <option value="4">English</option>
          <option value="5">Portuguese</option>
          <option value="6">Spanish</option>
          <option value="7">Hebrew</option>
          <option value="8">Italian</option>
          <option value="9">French</option>
        </select>  
      </div>
  </p>
</div>

 <!--summary-->   
<div class="u-form-group u-form-message u-label-top"> 
 <p>
    <label for="id_summary" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-4">DESCRIPTION</label>
    {% csrf_token %}
    <textarea name="summary" placeholder="BOOK DESCRIPTION" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-4"  cols="40" rows="10" maxlength="1000" required="" id="id_summary" control-id="ControlID-5"></textarea>
    <br>
    <span class="helptext">Enter a brief description of the book</span>   
 </p>
</div>

<!--Page number-->    
<div class="u-form-group u-form-number u-form-number-layout-number u-form-partition-factor-2 u-label-top u-form-group-5">
  <p>
  <label for="id_pg_num" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-5">PAGE NUMBER</label>
  <div class="u-input-row">
    {% csrf_token %}
    <input type="number" name="pg_num" required="" id="id_pg_num" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-5" control-id="ControlID-6">  
  </div>
  </p>
</div> 

<!--Status--> 
  <div class="u-form-group">   
  <p>
    <label for="id_status" class="u-custom-font u-font-montserrat u-label u-spacing-0 u-label-6">STATUS</label>
    <div class="u-form-select-wrapper">
      {% csrf_token %}
      <select name="status" required="" id="id_status" control-id="ControlID-7" class="u-custom-font u-font-montserrat u-grey-5 u-input u-input-rectangle u-radius-20 u-input-6">
        <option value="" selected="">---------</option>
        <option value="4">Reserved</option>
        <option value="5">Available</option>
        <option value="6">On_loan</option>
        <option value="7">Currently_reading</option>
        <option value="8">Next_in_line</option>
        <option value="9">Done_reading</option>
      </select>
    </div>
  </p>
</div>

<!--Submit-->    
{% csrf_token %}
  <input type="submit" value="Submit">
  


</form>
</div>
</div>
</section>  
</div> {% endcomment %}

{% include "partials/_footer.html" %}

<script class="u-script" type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}" defer=""></script>
<script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>

</body>
</html>


    

BookKeeper_app_root/templates/book_list.html
{%load static%}


<!DOCTYPE html>
<html style="font-size: 16px;" lang="pt">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="THE BOOKKEEPER">
    <meta name="description" content="">
    <title>BOOKSHELF</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css'%}" media="screen">
    <link rel="stylesheet" href="{% static 'css/BOOKSHELF.css'%}" media="screen">
    <meta name="generator" content="Nicepage 5.2.4, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Annie+Use+Your+Telescope:400">
    
    <meta name="theme-color" content="#a5abf0">
    <meta property="og:title" content="BOOKSHELF">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body u-overlap u-stick-footer u-xl-mode" data-lang="pt">
  

  {% include "partials/_navbar.html" %}

    <section class="u-clearfix u-section-1" id="sec-650c">

      <h2 class="u-text u-text-body-alt-color u-text-1"> MY BOOKSHELF</h2>

      <div class="u-list u-list-1">
        <div class="u-repeater u-repeater-1">
          <div class="u-align-center u-border-9 u-border-no-bottom u-border-no-left u-border-no-right u-border-palette-4-dark-1 u-bottom-left-radius-20 u-bottom-right-radius-20 u-container-style u-list-item u-palette-4-light-3 u-repeater-item u-shape-round u-video-cover u-list-item-1">
            <div class="u-container-layout u-similar-container u-valign-top u-container-layout-1">
              <img class="u-expanded-width u-image u-image-contain u-image-default u-preserve-proportions u-image-1" alt="" data-image-width="826" data-image-height="826" src= "{% static 'images/111.jpg' %}">
              <h4 class="u-text u-text-palette-1-dark-2 u-text-2">BOOK TITLE</h4>
              <a href=url (book_add) class="u-border-1 u-border-active-grey-70 u-border-black u-border-hover-grey-70 u-border-no-left u-border-no-right u-border-no-top u-bottom-left-radius-0 u-bottom-right-radius-0 u-btn u-button-style u-custom-item u-none u-radius-0 u-text-active-palette-2-base u-text-body-color u-text-hover-palette-2-base u-top-left-radius-0 u-top-right-radius-0 u-btn-1">more</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    
  {% include "partials/_footer.html" %}
  <script class="u-script" type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}" defer=""></script>
  <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>

</body>
</html>

BookKeeper_app_root/templates/myprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> profile test</h1>
</body>
</html>